// reimbursement.typ — Reimbursement claim PDF template.
//
// Renders a single-page reimbursement claim from submission data. Reads the
// data from `data.yml` in the same directory (the generator writes this
// alongside a copy of the template into a working dir before invoking typst).
//
// Reimbursements are contractor-level (PLAN §4.7): there is no contract
// reference. The PSL funding/billing code (`project`) is required and takes
// the metadata-band column a contract occupies on the other templates.
// Receipt files are committed to receipts/{period}/{submission_id}/ in the
// contractor repo and attached to the approval email; the PDF lists them by
// filename (no thumbnails — single-page constraint).
//
// Required data fields:
//   submission_id (str), type ("reimbursement"), period (str),
//   project (str — PSL funding/billing code),
//   submitted_date (str ISO), submitted_by (str), issue_number (int),
//   entries (list of {date, amount, amount_display, category, description}),
//   totals ({amount_amount_display, currency}),
//   trip_context (str, may be empty), receipts (list of {filename, source_url}),
//   notes (str, may be empty), status (str),
//   approved_by (str or none), approved_date (str ISO or none),
//   contractor ({name, github, email, address (optional)}),
//   fiscal_host ({psl_foundation: {name, address}, quantecon: {name, address}}).

#let data = yaml("data.yml")

// ── Palette ───────────────────────────────────────────────────────────────
#let primary  = rgb("#1a3a52")
#let accent   = rgb("#2b5f8a")
#let muted    = rgb("#6b7280")
#let rule     = rgb("#d1d5db")
#let panel    = rgb("#f3f6f9")
#let pending  = rgb("#b45309")
#let approved = rgb("#15803d")

// ── Page setup ────────────────────────────────────────────────────────────
#set page(
  paper: "a4",
  margin: (x: 1.8cm, top: 1.0cm, bottom: 1.0cm),
  footer: align(center)[
    #text(size: 7.5pt, fill: rgb("#6b7280"))[
      Generated by QuantEcon Contractor Payments ·
      #let repo = data.at("repo", default: none)
      #if repo != none {
        link("https://github.com/" + repo + "/issues/" + str(data.issue_number))[Issue \##data.issue_number]
      } else [
        Issue \##data.issue_number
      ]
    ]
  ],
)
#set text(size: 10pt, fill: rgb("#1f2937"))
#set par(justify: false, leading: 0.55em)

// ── Helpers ───────────────────────────────────────────────────────────────
#let label(content) = text(size: 7.5pt, fill: muted, tracking: 0.5pt)[
  #upper(content)
]
#let value(content) = text(size: 10pt, weight: "regular")[#content]

// ── Header: title bar, then logos + PSL address ───────────────────────────
#let psl_address = data.at("fiscal_host", default: (:)).at("psl_foundation", default: (:)).at("address", default: none)
#let qe_address  = data.at("fiscal_host", default: (:)).at("quantecon",       default: (:)).at("address", default: none)

#align(center)[
  #text(size: 15pt, weight: "bold", fill: primary, tracking: 2pt)[QUANTECON REIMBURSEMENT CLAIM]
]

#v(0.2cm)

// ── Revision banner ─────────────────────────────────────────────────────
// Surfaces when this submission supersedes a previous one (Phase 2.5).
// Single-line and concise; the full "no longer authoritative" prose lives
// in the supporting email body and audit comment.
#let supersedes_id = data.at("supersedes", default: none)
#if supersedes_id != none [
  #block(
    width: 100%,
    inset: (x: 12pt, y: 5pt),
    fill: rgb("#fed7aa"),
    stroke: (left: 3pt + rgb("#9a3412")),
    [
      #text(size: 10pt, weight: "bold", fill: rgb("#9a3412"))[⟳ REVISION] — #text(size: 10pt)[supersedes #raw(supersedes_id)]
    ]
  )
  #v(0.2cm)
]

#grid(
  columns: (auto, 1fr, auto),
  column-gutter: 0.6em,
  align: (left + top, left + top, right + top),
  image("assets/psl-foundation-logo.png", height: 1.3cm),
  if psl_address != none {
    text(size: 8.5pt, fill: muted)[#psl_address]
  } else { [] },
  block[
    #image("assets/quantecon-logo.png", height: 1.3cm)
    #if qe_address != none [
      #v(0.15cm)
      #text(size: 8.5pt, fill: muted)[#qe_address]
    ]
  ],
)

#v(0.35cm)

// ── Date + Claim ID (right-aligned, inline above the metadata band) ───────
#align(right)[
  #label("Date") #h(0.4em) #value[#data.submitted_date]

  #label("Claim") #h(0.4em) #value[#raw(data.submission_id)]
]

#v(0.15cm)

// ── Metadata band: Contractor | Project | Period ──────────────────────────
#let contractor_address = data.contractor.at("address", default: none)

#let column_stack(..items) = {
  set par(leading: 0.55em, spacing: 0.55em)
  let lines = items.pos().filter(x => x != none)
  for (i, line) in lines.enumerate() {
    line
    if i < lines.len() - 1 { linebreak() }
  }
}

#let contractor_cell = column_stack(
  [*#data.contractor.name*],
  [#data.contractor.email · `@`#data.contractor.github],
  if contractor_address != none { contractor_address } else { none },
)
// PSL funding/billing code — required for reimbursements (no contract to
// carry it); sourced from the repo's config/reimbursements.yml.
#let project_cell = column_stack([#data.project])
#let period_cell = column_stack([#data.period])

#block(
  width: 100%,
  inset: (x: 0pt, y: 5pt),
  stroke: (top: 0.5pt + rule, bottom: 0.5pt + rule),
  grid(
    columns: (1fr, 1fr, 1fr),
    column-gutter: 1.5em,
    row-gutter: 0.55em,
    stroke: (x, y) => if y == 0 { (bottom: 0.4pt + rule) } else { none },
    inset: (x: 0pt, y: 2pt),
    label("Contractor"),
    label("Project"),
    label("Period"),
    value[#contractor_cell],
    value[#project_cell],
    value[#period_cell],
  ),
)

#v(0.3cm)

// ── Expense entries table ─────────────────────────────────────────────────
#let header_row = (
  [#label("Date")],
  [#label("Category")],
  [#label("Description")],
  [#label("Amount")],
)
#let entry_rows = data.entries.map(e => (
  text(size: 9pt)[#e.date],
  text(size: 9pt)[#e.category],
  text(size: 9pt)[#e.description],
  align(right)[#text(size: 9pt)[#e.amount_display]],
)).flatten()

#table(
  columns: (auto, auto, 1fr, auto),
  align: (left + horizon, left + horizon, left + horizon, right + horizon),
  stroke: (x, y) => (
    bottom: if y == 0 { 0.75pt + primary } else { 0.4pt + rule },
  ),
  fill: (_, y) => if y == 0 { none } else if calc.odd(y) { panel } else { none },
  inset: (x: 8pt, y: 2.5pt),
  ..header_row,
  ..entry_rows,
)

#v(0.3cm)

// ── Totals panel — single Amount claimed row ──────────────────────────────
#let ccy = data.totals.at("currency", default: "")
#align(right)[
  #block(
    width: 8.0cm,
    inset: (x: 12pt, y: 8pt),
    fill: panel,
    stroke: (left: 3pt + primary),
    grid(
      columns: (1fr, auto, auto),
      column-gutter: (1.5em, 0.6em),
      row-gutter: 0.3em,
      align: (left, right, left),
      text(size: 10.5pt, fill: primary, weight: "bold")[Amount claimed],
        text(size: 12pt, fill: primary, weight: "bold")[#data.totals.amount_amount_display],
        text(size: 10.5pt, fill: primary, weight: "bold")[#ccy],
    ),
  )
]

#v(0.3cm)

// ── Trip / project context (if any) ───────────────────────────────────────
#if data.at("trip_context", default: "") != "" [
  #block(
    width: 100%,
    inset: (x: 8pt, y: 6pt),
    stroke: 0.5pt + rule,
    radius: 2pt,
    [
      #text(size: 8pt, fill: muted, tracking: 0.5pt)[#upper("Trip / project context")]
      #v(-0.05cm)
      #text(size: 9pt)[#data.trip_context]
    ],
  )
  #v(0.3cm)
]

// ── Receipts (committed to the contractor repo; attached to the email) ────
#let receipts = data.at("receipts", default: ())
#if receipts.len() > 0 [
  #block(
    width: 100%,
    inset: (x: 8pt, y: 6pt),
    stroke: 0.5pt + rule,
    radius: 2pt,
    [
      #text(size: 8pt, fill: muted, tracking: 0.5pt)[#upper("Receipts")]
      #h(0.5em)
      #text(size: 8pt, fill: muted)[(#receipts.len() file#if receipts.len() != 1 [s] — committed to #raw("receipts/" + data.period + "/" + data.submission_id + "/"), attached to the approval email)]
      #v(-0.05cm)
      #text(size: 9pt)[#receipts.map(r => raw(r.filename)).join(" · ")]
    ],
  )
  #v(0.3cm)
]

// ── Notes (if any) ────────────────────────────────────────────────────────
#if data.at("notes", default: "") != "" [
  #block(
    width: 100%,
    inset: (x: 8pt, y: 6pt),
    stroke: 0.5pt + rule,
    radius: 2pt,
    [
      #text(size: 8pt, fill: muted, tracking: 0.5pt)[#upper("Notes")]
      #v(-0.05cm)
      #text(size: 9pt)[#data.notes]
    ],
  )
  #v(0.3cm)
]

// ── Approval block ────────────────────────────────────────────────────────
#let is_pending = data.at("approved_by", default: none) == none

#block(
  width: 100%,
  inset: (x: 12pt, y: 9pt),
  fill: if is_pending { rgb("#fef3c7") } else { rgb("#dcfce7") },
  stroke: (left: 3pt + (if is_pending { pending } else { approved })),
  if is_pending [
    #text(size: 10pt, weight: "bold", fill: pending)[⚠ PENDING REVIEW] —
    #text(size: 9.5pt)[awaiting approval; this draft will be replaced with the approved version on merge.]
  ] else [
    #text(size: 10pt, weight: "bold", fill: approved)[✓ APPROVED] —
    #text(size: 9.5pt)[by `@`#data.approved_by on #data.approved_date.]
  ]
)
