// timesheet.typ — Hourly timesheet PDF template.
//
// Renders a single-page hourly timesheet from submission data. Reads the
// data from `data.yml` in the same directory (the generator writes this
// alongside a copy of the template into a working dir before invoking typst).
//
// Tuned to fit a 31-row month (worst-case) on a single A4 page.
//
// Required data fields:
//   submission_id (str), contract_id (str), type (str), period (str),
//   submitted_date (str ISO), submitted_by (str), issue_number (int),
//   entries (list of {date, hours, description, hours_display}),
//   totals ({hours_display, rate_display, amount_display}),
//   notes (str, may be empty), status (str),
//   approved_by (str or none), approved_date (str ISO or none),
//   contractor ({name, github, email}).

#let data = yaml("data.yml")

// ── Palette ───────────────────────────────────────────────────────────────
#let primary  = rgb("#1a3a52")   // PSL-leaning dark blue
#let accent   = rgb("#2b5f8a")
#let muted    = rgb("#6b7280")
#let rule     = rgb("#d1d5db")
#let panel    = rgb("#f3f6f9")
#let pending  = rgb("#b45309")   // amber for pending state
#let approved = rgb("#15803d")   // green for approved state

// ── Page setup ────────────────────────────────────────────────────────────
// Footer is page-level (lives in the bottom margin) so a content-heavy
// month doesn't push it to a second page.
#set page(
  paper: "a4",
  margin: (x: 1.8cm, top: 1.0cm, bottom: 1.0cm),
  footer: align(center)[
    #text(size: 7.5pt, fill: rgb("#6b7280"))[
      Generated by QuantEcon Timesheets · Issue \##data.issue_number ·
      Submission #data.submission_id
    ]
  ],
)
#set text(size: 10pt, fill: rgb("#1f2937"))
#set par(justify: false, leading: 0.55em)

// ── Helpers ───────────────────────────────────────────────────────────────
#let label(content) = text(size: 7.5pt, fill: muted, tracking: 0.5pt)[
  #upper(content)
]
#let value(content) = text(size: 10pt, weight: "regular")[#content]

// ── Header: logos + title ─────────────────────────────────────────────────
#grid(
  columns: (1fr, 1fr),
  align: (left + horizon, right + horizon),
  image("assets/quantecon-logo.png", height: 1.1cm),
  image("assets/psl-foundation-logo.png", height: 1.1cm),
)

#v(0.1cm)

#align(center)[
  #text(size: 18pt, weight: "bold", fill: primary, tracking: 1pt)[
    HOURLY TIMESHEET
  ]
]

#v(0.25cm)

// ── Metadata band ─────────────────────────────────────────────────────────
#block(
  width: 100%,
  inset: (x: 0pt, y: 5pt),
  stroke: (top: 0.5pt + rule, bottom: 0.5pt + rule),
  grid(
    columns: (1fr, 1fr, 1fr),
    column-gutter: 1.5em,
    row-gutter: 0.25em,
    label("Contractor"),
    label("Contract"),
    label("Submission"),
    value[*#data.contractor.name*],
    value[#data.contract_id],
    value[#data.submission_id],
    value[#data.contractor.email · `@`#data.contractor.github],
    value[Period #data.period],
    value[Submitted #data.submitted_date · `@`#data.submitted_by],
  ),
)

#v(0.3cm)

// ── Time entries table ────────────────────────────────────────────────────
#text(size: 10pt, weight: "bold", fill: primary)[Time Entries]
#v(0.15cm)

#let header_row = (
  [#label("Date")],
  [#label("Hours")],
  [#label("Description")],
)
#let entry_rows = data.entries.map(e => (
  text(size: 9pt)[#e.date],
  align(right)[#text(size: 9pt)[#e.hours_display]],
  text(size: 9pt)[#e.description],
)).flatten()

#table(
  columns: (auto, auto, 1fr),
  align: (left + horizon, right + horizon, left + horizon),
  stroke: (x, y) => (
    bottom: if y == 0 { 0.75pt + primary } else { 0.4pt + rule },
  ),
  fill: (_, y) => if y == 0 { none } else if calc.odd(y) { panel } else { none },
  inset: (x: 8pt, y: 2.5pt),
  ..header_row,
  ..entry_rows,
)

#v(0.3cm)

// ── Totals panel ──────────────────────────────────────────────────────────
#align(right)[
  #block(
    width: 7.5cm,
    inset: (x: 12pt, y: 8pt),
    fill: panel,
    stroke: (left: 3pt + primary),
    grid(
      columns: (1fr, auto),
      column-gutter: 1.5em,
      row-gutter: 0.3em,
      text(size: 9.5pt, fill: muted)[Total hours], text(size: 9.5pt, weight: "medium")[#data.totals.hours_display],
      text(size: 9.5pt, fill: muted)[Hourly rate],  text(size: 9.5pt, weight: "medium")[#data.totals.rate_display],
      grid.cell(colspan: 2, line(length: 100%, stroke: 0.5pt + rule)),
      text(size: 10.5pt, fill: primary, weight: "bold")[Amount payable],
      text(size: 12pt, fill: primary, weight: "bold")[#data.totals.amount_display],
    ),
  )
]

#v(0.3cm)

// ── Notes (if any) ────────────────────────────────────────────────────────
#if data.at("notes", default: "") != "" [
  #block(
    width: 100%,
    inset: (x: 8pt, y: 6pt),
    stroke: 0.5pt + rule,
    radius: 2pt,
    [
      #text(size: 8pt, fill: muted, tracking: 0.5pt)[#upper("Notes")]
      #v(-0.05cm)
      #text(size: 9pt)[#data.notes]
    ],
  )
  #v(0.3cm)
]

// ── Approval block ────────────────────────────────────────────────────────
#let is_pending = data.at("approved_by", default: none) == none

#block(
  width: 100%,
  inset: (x: 12pt, y: 9pt),
  fill: if is_pending { rgb("#fef3c7") } else { rgb("#dcfce7") },
  stroke: (left: 3pt + (if is_pending { pending } else { approved })),
  if is_pending [
    #text(size: 10pt, weight: "bold", fill: pending)[⚠ PENDING REVIEW] —
    #text(size: 9.5pt)[awaiting approval; this draft will be replaced with the approved version on merge.]
  ] else [
    #text(size: 10pt, weight: "bold", fill: approved)[✓ APPROVED] —
    #text(size: 9.5pt)[by `@`#data.approved_by on #data.approved_date.]
  ]
)

