// timesheet.typ — Hourly timesheet PDF template.
//
// Renders a single-page hourly timesheet from submission data. Reads the
// data from `data.yml` in the same directory (the generator writes this
// alongside a copy of the template into a working dir before invoking typst).
//
// Tuned to fit a 31-row month (worst-case) on a single A4 page.
//
// Required data fields:
//   submission_id (str), contract_id (str), type (str), period (str),
//   contract_start_date (str ISO), contract_end_date (str ISO),
//   submitted_date (str ISO), submitted_by (str), issue_number (int),
//   entries (list of {date, hours, description, hours_display}),
//   totals ({hours_display, rate_amount_display, amount_amount_display, currency}),
//   notes (str, may be empty), status (str),
//   approved_by (str or none), approved_date (str ISO or none),
//   contractor ({name, github, email, address (optional)}),
//   fiscal_host ({psl_foundation: {name, address}, quantecon: {name, address}}).

#let data = yaml("data.yml")

// ── Palette ───────────────────────────────────────────────────────────────
#let primary  = rgb("#1a3a52")   // PSL-leaning dark blue
#let accent   = rgb("#2b5f8a")
#let muted    = rgb("#6b7280")
#let rule     = rgb("#d1d5db")
#let panel    = rgb("#f3f6f9")
#let pending  = rgb("#b45309")   // amber for pending state
#let approved = rgb("#15803d")   // green for approved state

// ── Page setup ────────────────────────────────────────────────────────────
// Footer is page-level (lives in the bottom margin) so a content-heavy
// month doesn't push it to a second page.
#set page(
  paper: "a4",
  margin: (x: 1.8cm, top: 1.0cm, bottom: 1.0cm),
  footer: align(center)[
    #text(size: 7.5pt, fill: rgb("#6b7280"))[
      Generated by QuantEcon Timesheets ·
      #let repo = data.at("repo", default: none)
      #if repo != none {
        link("https://github.com/" + repo + "/issues/" + str(data.issue_number))[Issue \##data.issue_number]
      } else [
        Issue \##data.issue_number
      ]
    ]
  ],
)
#set text(size: 10pt, fill: rgb("#1f2937"))
#set par(justify: false, leading: 0.55em)

// ── Helpers ───────────────────────────────────────────────────────────────
#let label(content) = text(size: 7.5pt, fill: muted, tracking: 0.5pt)[
  #upper(content)
]
#let value(content) = text(size: 10pt, weight: "regular")[#content]

// ── Header: title bar, then logos + PSL address ───────────────────────────
#let psl_address = data.at("fiscal_host", default: (:)).at("psl_foundation", default: (:)).at("address", default: none)
#let qe_address  = data.at("fiscal_host", default: (:)).at("quantecon",       default: (:)).at("address", default: none)

#align(center)[
  #text(size: 15pt, weight: "bold", fill: primary, tracking: 2pt)[QUANTECON TIMESHEET]
]

#v(0.2cm)

#grid(
  columns: (auto, 1fr, auto),
  column-gutter: 0.6em,
  align: (left + top, left + top, right + top),
  image("assets/psl-foundation-logo.png", height: 1.3cm),
  if psl_address != none {
    text(size: 8.5pt, fill: muted)[#psl_address]
  } else { [] },
  block[
    #image("assets/quantecon-logo.png", height: 1.3cm)
    #if qe_address != none [
      #v(0.15cm)
      #text(size: 8.5pt, fill: muted)[#qe_address]
    ]
  ],
)

#v(0.35cm)

// ── Date (right-aligned, inline above the metadata band) ──────────────────
#align(right)[
  #label("Date") #h(0.4em) #value[#data.submitted_date]
]

#v(0.15cm)

// ── Metadata band ─────────────────────────────────────────────────────────
#let contractor_address = data.contractor.at("address", default: none)
#let contract_window = if data.at("contract_start_date", default: none) != none and data.at("contract_end_date", default: none) != none {
  [#data.contract_start_date → #data.contract_end_date]
} else {
  [—]
}

// Stack each column's values inside a single cell with a unified par-leading,
// so the gaps between name/email/address (and between contract id/window,
// submission id/period) are governed by one consistent line-height instead of
// a grid row-gutter that varies with the rendered text size.
#let column_stack(..items) = {
  set par(leading: 0.55em, spacing: 0.55em)
  let lines = items.pos().filter(x => x != none)
  for (i, line) in lines.enumerate() {
    line
    if i < lines.len() - 1 { linebreak() }
  }
}

#let contractor_cell = column_stack(
  [*#data.contractor.name*],
  [#data.contractor.email · `@`#data.contractor.github],
  if contractor_address != none { contractor_address } else { none },
)
#let contract_cell = column_stack([#data.contract_id], contract_window)
#let period_cell = column_stack([#data.period])

#block(
  width: 100%,
  inset: (x: 0pt, y: 5pt),
  stroke: (top: 0.5pt + rule, bottom: 0.5pt + rule),
  grid(
    columns: (1fr, 1fr, 1fr),
    column-gutter: 1.5em,
    row-gutter: 0.55em,
    stroke: (x, y) => if y == 0 { (bottom: 0.4pt + rule) } else { none },
    inset: (x: 0pt, y: 2pt),
    label("Contractor"),
    label("Contract"),
    label("Period"),
    value[#contractor_cell],
    value[#contract_cell],
    value[#period_cell],
  ),
)

#v(0.3cm)

#let header_row = (
  [#label("Date")],
  [#label("Hours")],
  [#label("Description")],
)
#let entry_rows = data.entries.map(e => (
  text(size: 9pt)[#e.date],
  align(right)[#text(size: 9pt)[#e.hours_display]],
  text(size: 9pt)[#e.description],
)).flatten()

#table(
  columns: (auto, auto, 1fr),
  align: (left + horizon, right + horizon, left + horizon),
  stroke: (x, y) => (
    bottom: if y == 0 { 0.75pt + primary } else { 0.4pt + rule },
  ),
  fill: (_, y) => if y == 0 { none } else if calc.odd(y) { panel } else { none },
  inset: (x: 8pt, y: 2.5pt),
  ..header_row,
  ..entry_rows,
)

#v(0.3cm)

// ── Totals panel ──────────────────────────────────────────────────────────
#let ccy = data.totals.at("currency", default: "")
#align(right)[
  #block(
    width: 8.0cm,
    inset: (x: 12pt, y: 8pt),
    fill: panel,
    stroke: (left: 3pt + primary),
    grid(
      columns: (1fr, auto, auto),
      column-gutter: (1.5em, 0.6em),
      row-gutter: 0.3em,
      align: (left, right, left),
      text(size: 9.5pt, fill: muted)[Total hours],
        text(size: 9.5pt, weight: "medium")[#data.totals.hours_display], [],
      text(size: 9.5pt, fill: muted)[Hourly rate],
        text(size: 9.5pt, weight: "medium")[#data.totals.rate_amount_display],
        [],
      grid.cell(colspan: 3, line(length: 100%, stroke: 0.5pt + rule)),
      text(size: 10.5pt, fill: primary, weight: "bold")[Amount payable],
        text(size: 12pt, fill: primary, weight: "bold")[#data.totals.amount_amount_display],
        text(size: 10.5pt, fill: primary, weight: "bold")[#ccy],
    ),
  )
]

#v(0.3cm)

// ── Notes (if any) ────────────────────────────────────────────────────────
#if data.at("notes", default: "") != "" [
  #block(
    width: 100%,
    inset: (x: 8pt, y: 6pt),
    stroke: 0.5pt + rule,
    radius: 2pt,
    [
      #text(size: 8pt, fill: muted, tracking: 0.5pt)[#upper("Notes")]
      #v(-0.05cm)
      #text(size: 9pt)[#data.notes]
    ],
  )
  #v(0.3cm)
]

// ── Approval block ────────────────────────────────────────────────────────
#let is_pending = data.at("approved_by", default: none) == none

#block(
  width: 100%,
  inset: (x: 12pt, y: 9pt),
  fill: if is_pending { rgb("#fef3c7") } else { rgb("#dcfce7") },
  stroke: (left: 3pt + (if is_pending { pending } else { approved })),
  if is_pending [
    #text(size: 10pt, weight: "bold", fill: pending)[⚠ PENDING REVIEW] —
    #text(size: 9.5pt)[awaiting approval; this draft will be replaced with the approved version on merge.]
  ] else [
    #text(size: 10pt, weight: "bold", fill: approved)[✓ APPROVED] —
    #text(size: 9.5pt)[by `@`#data.approved_by on #data.approved_date.]
  ]
)

